/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ReportUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportUpdate{}

// ReportUpdate struct for ReportUpdate
type ReportUpdate struct {
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// NewReportUpdate instantiates a new ReportUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportUpdate() *ReportUpdate {
	this := ReportUpdate{}
	return &this
}

// NewReportUpdateWithDefaults instantiates a new ReportUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportUpdateWithDefaults() *ReportUpdate {
	this := ReportUpdate{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ReportUpdate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportUpdate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ReportUpdate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ReportUpdate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o ReportUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableReportUpdate struct {
	value *ReportUpdate
	isSet bool
}

func (v NullableReportUpdate) Get() *ReportUpdate {
	return v.value
}

func (v *NullableReportUpdate) Set(val *ReportUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableReportUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableReportUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportUpdate(val *ReportUpdate) *NullableReportUpdate {
	return &NullableReportUpdate{value: val, isSet: true}
}

func (v NullableReportUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


