/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceUpdate{}

// InstanceUpdate struct for InstanceUpdate
type InstanceUpdate struct {
	Notes string `json:"notes"`
}

type _InstanceUpdate InstanceUpdate

// NewInstanceUpdate instantiates a new InstanceUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceUpdate(notes string) *InstanceUpdate {
	this := InstanceUpdate{}
	this.Notes = notes
	return &this
}

// NewInstanceUpdateWithDefaults instantiates a new InstanceUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceUpdateWithDefaults() *InstanceUpdate {
	this := InstanceUpdate{}
	return &this
}

// GetNotes returns the Notes field value
func (o *InstanceUpdate) GetNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value
// and a boolean to check if the value has been set.
func (o *InstanceUpdate) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notes, true
}

// SetNotes sets field value
func (o *InstanceUpdate) SetNotes(v string) {
	o.Notes = v
}

func (o InstanceUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["notes"] = o.Notes
	return toSerialize, nil
}

func (o *InstanceUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"notes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceUpdate := _InstanceUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceUpdate)

	if err != nil {
		return err
	}

	*o = InstanceUpdate(varInstanceUpdate)

	return err
}

type NullableInstanceUpdate struct {
	value *InstanceUpdate
	isSet bool
}

func (v NullableInstanceUpdate) Get() *InstanceUpdate {
	return v.value
}

func (v *NullableInstanceUpdate) Set(val *InstanceUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceUpdate(val *InstanceUpdate) *NullableInstanceUpdate {
	return &NullableInstanceUpdate{value: val, isSet: true}
}

func (v NullableInstanceUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


