/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceCreate{}

// InstanceCreate struct for InstanceCreate
type InstanceCreate struct {
	ProjectId string `json:"project_id"`
	Notes NullableString `json:"notes,omitempty"`
}

type _InstanceCreate InstanceCreate

// NewInstanceCreate instantiates a new InstanceCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceCreate(projectId string) *InstanceCreate {
	this := InstanceCreate{}
	this.ProjectId = projectId
	return &this
}

// NewInstanceCreateWithDefaults instantiates a new InstanceCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceCreateWithDefaults() *InstanceCreate {
	this := InstanceCreate{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *InstanceCreate) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *InstanceCreate) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *InstanceCreate) SetProjectId(v string) {
	o.ProjectId = v
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InstanceCreate) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InstanceCreate) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *InstanceCreate) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *InstanceCreate) SetNotes(v string) {
	o.Notes.Set(&v)
}
// SetNotesNil sets the value for Notes to be an explicit nil
func (o *InstanceCreate) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *InstanceCreate) UnsetNotes() {
	o.Notes.Unset()
}

func (o InstanceCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	return toSerialize, nil
}

func (o *InstanceCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceCreate := _InstanceCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceCreate)

	if err != nil {
		return err
	}

	*o = InstanceCreate(varInstanceCreate)

	return err
}

type NullableInstanceCreate struct {
	value *InstanceCreate
	isSet bool
}

func (v NullableInstanceCreate) Get() *InstanceCreate {
	return v.value
}

func (v *NullableInstanceCreate) Set(val *InstanceCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceCreate(val *InstanceCreate) *NullableInstanceCreate {
	return &NullableInstanceCreate{value: val, isSet: true}
}

func (v NullableInstanceCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


