/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectOut{}

// ProjectOut struct for ProjectOut
type ProjectOut struct {
	Uuid string `json:"uuid"`
	ProjectId string `json:"project_id"`
	Name string `json:"name"`
}

type _ProjectOut ProjectOut

// NewProjectOut instantiates a new ProjectOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectOut(uuid string, projectId string, name string) *ProjectOut {
	this := ProjectOut{}
	this.Uuid = uuid
	this.ProjectId = projectId
	this.Name = name
	return &this
}

// NewProjectOutWithDefaults instantiates a new ProjectOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectOutWithDefaults() *ProjectOut {
	this := ProjectOut{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *ProjectOut) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ProjectOut) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ProjectOut) SetUuid(v string) {
	o.Uuid = v
}

// GetProjectId returns the ProjectId field value
func (o *ProjectOut) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ProjectOut) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ProjectOut) SetProjectId(v string) {
	o.ProjectId = v
}

// GetName returns the Name field value
func (o *ProjectOut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectOut) SetName(v string) {
	o.Name = v
}

func (o ProjectOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["project_id"] = o.ProjectId
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ProjectOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"project_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectOut := _ProjectOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectOut)

	if err != nil {
		return err
	}

	*o = ProjectOut(varProjectOut)

	return err
}

type NullableProjectOut struct {
	value *ProjectOut
	isSet bool
}

func (v NullableProjectOut) Get() *ProjectOut {
	return v.value
}

func (v *NullableProjectOut) Set(val *ProjectOut) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectOut) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectOut(val *ProjectOut) *NullableProjectOut {
	return &NullableProjectOut{value: val, isSet: true}
}

func (v NullableProjectOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


