/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceQueryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceQueryResponse{}

// InstanceQueryResponse struct for InstanceQueryResponse
type InstanceQueryResponse struct {
	Items []InstanceOut `json:"items"`
	Total int32 `json:"total"`
	Page int32 `json:"page"`
	Resultsperpage int32 `json:"resultsperpage"`
}

type _InstanceQueryResponse InstanceQueryResponse

// NewInstanceQueryResponse instantiates a new InstanceQueryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceQueryResponse(items []InstanceOut, total int32, page int32, resultsperpage int32) *InstanceQueryResponse {
	this := InstanceQueryResponse{}
	this.Items = items
	this.Total = total
	this.Page = page
	this.Resultsperpage = resultsperpage
	return &this
}

// NewInstanceQueryResponseWithDefaults instantiates a new InstanceQueryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceQueryResponseWithDefaults() *InstanceQueryResponse {
	this := InstanceQueryResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *InstanceQueryResponse) GetItems() []InstanceOut {
	if o == nil {
		var ret []InstanceOut
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *InstanceQueryResponse) GetItemsOk() ([]InstanceOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *InstanceQueryResponse) SetItems(v []InstanceOut) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *InstanceQueryResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *InstanceQueryResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *InstanceQueryResponse) SetTotal(v int32) {
	o.Total = v
}

// GetPage returns the Page field value
func (o *InstanceQueryResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *InstanceQueryResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *InstanceQueryResponse) SetPage(v int32) {
	o.Page = v
}

// GetResultsperpage returns the Resultsperpage field value
func (o *InstanceQueryResponse) GetResultsperpage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Resultsperpage
}

// GetResultsperpageOk returns a tuple with the Resultsperpage field value
// and a boolean to check if the value has been set.
func (o *InstanceQueryResponse) GetResultsperpageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resultsperpage, true
}

// SetResultsperpage sets field value
func (o *InstanceQueryResponse) SetResultsperpage(v int32) {
	o.Resultsperpage = v
}

func (o InstanceQueryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceQueryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["resultsperpage"] = o.Resultsperpage
	return toSerialize, nil
}

func (o *InstanceQueryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
		"page",
		"resultsperpage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceQueryResponse := _InstanceQueryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceQueryResponse)

	if err != nil {
		return err
	}

	*o = InstanceQueryResponse(varInstanceQueryResponse)

	return err
}

type NullableInstanceQueryResponse struct {
	value *InstanceQueryResponse
	isSet bool
}

func (v NullableInstanceQueryResponse) Get() *InstanceQueryResponse {
	return v.value
}

func (v *NullableInstanceQueryResponse) Set(val *InstanceQueryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceQueryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceQueryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceQueryResponse(val *InstanceQueryResponse) *NullableInstanceQueryResponse {
	return &NullableInstanceQueryResponse{value: val, isSet: true}
}

func (v NullableInstanceQueryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceQueryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


