/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReportCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportCreate{}

// ReportCreate struct for ReportCreate
type ReportCreate struct {
	InstanceUuid string `json:"instance_uuid"`
	Severity string `json:"severity" validate:"regexp=^(low|medium|high|critical)$"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _ReportCreate ReportCreate

// NewReportCreate instantiates a new ReportCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportCreate(instanceUuid string, severity string) *ReportCreate {
	this := ReportCreate{}
	this.InstanceUuid = instanceUuid
	this.Severity = severity
	return &this
}

// NewReportCreateWithDefaults instantiates a new ReportCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportCreateWithDefaults() *ReportCreate {
	this := ReportCreate{}
	return &this
}

// GetInstanceUuid returns the InstanceUuid field value
func (o *ReportCreate) GetInstanceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceUuid
}

// GetInstanceUuidOk returns a tuple with the InstanceUuid field value
// and a boolean to check if the value has been set.
func (o *ReportCreate) GetInstanceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceUuid, true
}

// SetInstanceUuid sets field value
func (o *ReportCreate) SetInstanceUuid(v string) {
	o.InstanceUuid = v
}

// GetSeverity returns the Severity field value
func (o *ReportCreate) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *ReportCreate) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *ReportCreate) SetSeverity(v string) {
	o.Severity = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ReportCreate) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportCreate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ReportCreate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *ReportCreate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o ReportCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instance_uuid"] = o.InstanceUuid
	toSerialize["severity"] = o.Severity
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *ReportCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instance_uuid",
		"severity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportCreate := _ReportCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReportCreate)

	if err != nil {
		return err
	}

	*o = ReportCreate(varReportCreate)

	return err
}

type NullableReportCreate struct {
	value *ReportCreate
	isSet bool
}

func (v NullableReportCreate) Get() *ReportCreate {
	return v.value
}

func (v *NullableReportCreate) Set(val *ReportCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableReportCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableReportCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportCreate(val *ReportCreate) *NullableReportCreate {
	return &NullableReportCreate{value: val, isSet: true}
}

func (v NullableReportCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


