/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceOut{}

// InstanceOut struct for InstanceOut
type InstanceOut struct {
	Uuid string `json:"uuid"`
	ProjectUuid string `json:"project_uuid"`
	Notes string `json:"notes"`
}

type _InstanceOut InstanceOut

// NewInstanceOut instantiates a new InstanceOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceOut(uuid string, projectUuid string, notes string) *InstanceOut {
	this := InstanceOut{}
	this.Uuid = uuid
	this.ProjectUuid = projectUuid
	this.Notes = notes
	return &this
}

// NewInstanceOutWithDefaults instantiates a new InstanceOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceOutWithDefaults() *InstanceOut {
	this := InstanceOut{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *InstanceOut) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *InstanceOut) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *InstanceOut) SetUuid(v string) {
	o.Uuid = v
}

// GetProjectUuid returns the ProjectUuid field value
func (o *InstanceOut) GetProjectUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectUuid
}

// GetProjectUuidOk returns a tuple with the ProjectUuid field value
// and a boolean to check if the value has been set.
func (o *InstanceOut) GetProjectUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectUuid, true
}

// SetProjectUuid sets field value
func (o *InstanceOut) SetProjectUuid(v string) {
	o.ProjectUuid = v
}

// GetNotes returns the Notes field value
func (o *InstanceOut) GetNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value
// and a boolean to check if the value has been set.
func (o *InstanceOut) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notes, true
}

// SetNotes sets field value
func (o *InstanceOut) SetNotes(v string) {
	o.Notes = v
}

func (o InstanceOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["project_uuid"] = o.ProjectUuid
	toSerialize["notes"] = o.Notes
	return toSerialize, nil
}

func (o *InstanceOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"project_uuid",
		"notes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceOut := _InstanceOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceOut)

	if err != nil {
		return err
	}

	*o = InstanceOut(varInstanceOut)

	return err
}

type NullableInstanceOut struct {
	value *InstanceOut
	isSet bool
}

func (v NullableInstanceOut) Get() *InstanceOut {
	return v.value
}

func (v *NullableInstanceOut) Set(val *InstanceOut) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceOut) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceOut(val *InstanceOut) *NullableInstanceOut {
	return &NullableInstanceOut{value: val, isSet: true}
}

func (v NullableInstanceOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


