/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ReportOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportOut{}

// ReportOut struct for ReportOut
type ReportOut struct {
	Uuid string `json:"uuid"`
	ProjectUuid string `json:"project_uuid"`
	InstanceUuid string `json:"instance_uuid"`
	Timestamp time.Time `json:"timestamp"`
	Severity string `json:"severity"`
	Metadata map[string]interface{} `json:"metadata"`
}

type _ReportOut ReportOut

// NewReportOut instantiates a new ReportOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportOut(uuid string, projectUuid string, instanceUuid string, timestamp time.Time, severity string, metadata map[string]interface{}) *ReportOut {
	this := ReportOut{}
	this.Uuid = uuid
	this.ProjectUuid = projectUuid
	this.InstanceUuid = instanceUuid
	this.Timestamp = timestamp
	this.Severity = severity
	this.Metadata = metadata
	return &this
}

// NewReportOutWithDefaults instantiates a new ReportOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportOutWithDefaults() *ReportOut {
	this := ReportOut{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *ReportOut) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ReportOut) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ReportOut) SetUuid(v string) {
	o.Uuid = v
}

// GetProjectUuid returns the ProjectUuid field value
func (o *ReportOut) GetProjectUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectUuid
}

// GetProjectUuidOk returns a tuple with the ProjectUuid field value
// and a boolean to check if the value has been set.
func (o *ReportOut) GetProjectUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectUuid, true
}

// SetProjectUuid sets field value
func (o *ReportOut) SetProjectUuid(v string) {
	o.ProjectUuid = v
}

// GetInstanceUuid returns the InstanceUuid field value
func (o *ReportOut) GetInstanceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceUuid
}

// GetInstanceUuidOk returns a tuple with the InstanceUuid field value
// and a boolean to check if the value has been set.
func (o *ReportOut) GetInstanceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceUuid, true
}

// SetInstanceUuid sets field value
func (o *ReportOut) SetInstanceUuid(v string) {
	o.InstanceUuid = v
}

// GetTimestamp returns the Timestamp field value
func (o *ReportOut) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *ReportOut) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *ReportOut) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetSeverity returns the Severity field value
func (o *ReportOut) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *ReportOut) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *ReportOut) SetSeverity(v string) {
	o.Severity = v
}

// GetMetadata returns the Metadata field value
func (o *ReportOut) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *ReportOut) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *ReportOut) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o ReportOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["project_uuid"] = o.ProjectUuid
	toSerialize["instance_uuid"] = o.InstanceUuid
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["severity"] = o.Severity
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *ReportOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"project_uuid",
		"instance_uuid",
		"timestamp",
		"severity",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportOut := _ReportOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReportOut)

	if err != nil {
		return err
	}

	*o = ReportOut(varReportOut)

	return err
}

type NullableReportOut struct {
	value *ReportOut
	isSet bool
}

func (v NullableReportOut) Get() *ReportOut {
	return v.value
}

func (v *NullableReportOut) Set(val *ReportOut) {
	v.value = val
	v.isSet = true
}

func (v NullableReportOut) IsSet() bool {
	return v.isSet
}

func (v *NullableReportOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportOut(val *ReportOut) *NullableReportOut {
	return &NullableReportOut{value: val, isSet: true}
}

func (v NullableReportOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


