/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InstanceCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceCreateResponse{}

// InstanceCreateResponse struct for InstanceCreateResponse
type InstanceCreateResponse struct {
	InstanceUuid string `json:"instance_uuid"`
	Token string `json:"token"`
}

type _InstanceCreateResponse InstanceCreateResponse

// NewInstanceCreateResponse instantiates a new InstanceCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceCreateResponse(instanceUuid string, token string) *InstanceCreateResponse {
	this := InstanceCreateResponse{}
	this.InstanceUuid = instanceUuid
	this.Token = token
	return &this
}

// NewInstanceCreateResponseWithDefaults instantiates a new InstanceCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceCreateResponseWithDefaults() *InstanceCreateResponse {
	this := InstanceCreateResponse{}
	return &this
}

// GetInstanceUuid returns the InstanceUuid field value
func (o *InstanceCreateResponse) GetInstanceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceUuid
}

// GetInstanceUuidOk returns a tuple with the InstanceUuid field value
// and a boolean to check if the value has been set.
func (o *InstanceCreateResponse) GetInstanceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceUuid, true
}

// SetInstanceUuid sets field value
func (o *InstanceCreateResponse) SetInstanceUuid(v string) {
	o.InstanceUuid = v
}

// GetToken returns the Token field value
func (o *InstanceCreateResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *InstanceCreateResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *InstanceCreateResponse) SetToken(v string) {
	o.Token = v
}

func (o InstanceCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["instance_uuid"] = o.InstanceUuid
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *InstanceCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instance_uuid",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstanceCreateResponse := _InstanceCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInstanceCreateResponse)

	if err != nil {
		return err
	}

	*o = InstanceCreateResponse(varInstanceCreateResponse)

	return err
}

type NullableInstanceCreateResponse struct {
	value *InstanceCreateResponse
	isSet bool
}

func (v NullableInstanceCreateResponse) Get() *InstanceCreateResponse {
	return v.value
}

func (v *NullableInstanceCreateResponse) Set(val *InstanceCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceCreateResponse(val *InstanceCreateResponse) *NullableInstanceCreateResponse {
	return &NullableInstanceCreateResponse{value: val, isSet: true}
}

func (v NullableInstanceCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


