/*
Crash Reporter API

API for receiving and managing crash reports.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserOut{}

// UserOut struct for UserOut
type UserOut struct {
	Uuid string `json:"uuid"`
	Username string `json:"username"`
}

type _UserOut UserOut

// NewUserOut instantiates a new UserOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserOut(uuid string, username string) *UserOut {
	this := UserOut{}
	this.Uuid = uuid
	this.Username = username
	return &this
}

// NewUserOutWithDefaults instantiates a new UserOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserOutWithDefaults() *UserOut {
	this := UserOut{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *UserOut) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *UserOut) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *UserOut) SetUuid(v string) {
	o.Uuid = v
}

// GetUsername returns the Username field value
func (o *UserOut) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserOut) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserOut) SetUsername(v string) {
	o.Username = v
}

func (o UserOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *UserOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserOut := _UserOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserOut)

	if err != nil {
		return err
	}

	*o = UserOut(varUserOut)

	return err
}

type NullableUserOut struct {
	value *UserOut
	isSet bool
}

func (v NullableUserOut) Get() *UserOut {
	return v.value
}

func (v *NullableUserOut) Set(val *UserOut) {
	v.value = val
	v.isSet = true
}

func (v NullableUserOut) IsSet() bool {
	return v.isSet
}

func (v *NullableUserOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserOut(val *UserOut) *NullableUserOut {
	return &NullableUserOut{value: val, isSet: true}
}

func (v NullableUserOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


